[project]
name = "jad-oai-pmh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "acdh-tei-pyutils>=1.6",
    "jinja2>=3.1.6",
]

[dependency-groups]
dev = [
    "ruff>=0.13.2",
]
